(function() {var implementors = {};
implementors["image_processor"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"image_processor/OwnedImage/struct.OwnedImage.html\" title=\"struct image_processor::OwnedImage::OwnedImage\">OwnedImage</a>",synthetic:true,types:["image_processor::OwnedImage::OwnedImage"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"image_processor/ImageSlice/struct.ImageSlice.html\" title=\"struct image_processor::ImageSlice::ImageSlice\">ImageSlice</a>&lt;'a&gt;",synthetic:true,types:["image_processor::ImageSlice::ImageSlice"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"image_processor/ImageSlice/struct.ImageSliceMut.html\" title=\"struct image_processor::ImageSlice::ImageSliceMut\">ImageSliceMut</a>&lt;'a&gt;",synthetic:true,types:["image_processor::ImageSlice::ImageSliceMut"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"image_processor/utils/struct.Dimensions.html\" title=\"struct image_processor::utils::Dimensions\">Dimensions</a>",synthetic:true,types:["image_processor::utils::Dimensions"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"image_processor/utils/struct.Pixel.html\" title=\"struct image_processor::utils::Pixel\">Pixel</a>",synthetic:true,types:["image_processor::utils::Pixel"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"image_processor/utils/struct.SliceSpec.html\" title=\"struct image_processor::utils::SliceSpec\">SliceSpec</a>",synthetic:true,types:["image_processor::utils::SliceSpec"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"enum\" href=\"image_processor/utils/enum.ImageError.html\" title=\"enum image_processor::utils::ImageError\">ImageError</a>",synthetic:true,types:["image_processor::utils::ImageError"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
